# Use uma imagem base do Python
FROM python:3.9-slim-buster

# Crie o diretório de trabalho
WORKDIR /app

# Copie o requirements.txt e instale as dependências
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copie os arquivos da aplicação
COPY . .

# Exponha a porta 5000 (exemplo)
EXPOSE 5000

# Comando para executar a aplicação
CMD ["python", "visualização_de_dados_financeiros.py"]
