FROM python:3.9.13-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN apt-get update && \
    apt-get install -y build-essential && \
    pip install -r requirements.txt

# Criar um usuário não-root (exemplo)
RUN useradd -ms /bin/bash appuser

USER appuser

COPY . .

# Definir ponto de entrada e comando
ENTRYPOINT ["python3"]
CMD ["visualização_de_dados_financeiros.py"]
